# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20161103_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='verified_by',
            new_name='create_by',
        ),
    ]
