# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20161106_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(default='assets/img/news/h1.jpg', max_length=100),
        ),
    ]
