# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('device_type', models.CharField(max_length=10)),
                ('access_time', models.DateTimeField(auto_now=True)),
                ('language_code', models.CharField(max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('phone_token', models.CharField(max_length=200)),
                ('phone_type', models.CharField(max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=400, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('extension', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useraddress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('account_id', models.CharField(max_length=50, null=True)),
                ('account_key', models.CharField(max_length=100, null=True)),
                ('account_secret', models.CharField(max_length=100, null=True)),
                ('request_permission', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(default=0)),
                ('firm_name', models.CharField(max_length=100)),
                ('web_site', models.CharField(blank=True, max_length=200, null=True)),
                ('public_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('public_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('service_provided', models.CharField(blank=True, max_length=400, null=True)),
                ('area_served', models.CharField(blank=True, max_length=400, null=True)),
                ('certification_awards', models.CharField(blank=True, max_length=400, null=True)),
                ('affiliations', models.TextField(blank=True, null=True)),
                ('contact_address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_province', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_country', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_fax', models.CharField(blank=True, max_length=15, null=True)),
                ('additional_emails', models.CharField(blank=True, max_length=400, null=True)),
                ('date_last_update', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('status_code', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.SellerCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLoginAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_user_id', models.CharField(max_length=30)),
                ('access_token', models.CharField(max_length=100, null=True)),
                ('granted_permissions', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_canceled', models.DateTimeField(auto_now_add=True)),
                ('login_account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.LoginAccountType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('about_me', models.CharField(blank=True, max_length=400, null=True)),
                ('next_house_project', models.CharField(blank=True, max_length=400, null=True)),
                ('contact_city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_country', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_province', models.CharField(blank=True, max_length=100, null=True)),
                ('image_cover', models.CharField(blank=True, max_length=100, null=True)),
                ('date_last_update', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SellerCategory'),
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
