# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='category',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellercategory',
            name='parent',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='contact_city',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_province',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='next_house_project',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_code',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='SellerCategory',
        ),
    ]
